const os=require('os');
console.log(os.totalmem());
console.log(os.freemem());
console.log(os.arch());
console.log(os.release());
console.log(os.platform());
console.log(os.cpus().length);
console.log(os.uptime());
console.log(os.tmpdir());
console.log(os.version());
console.log(os.type());
console.log(os.homedir());
console.log(os.EOL);
console.log(os.hostname());
console.log(os.constants);